### PR TITLE
Update all files from source

### PR DESCRIPTION
**Pull request by SaveTheRbtz**
While here, also fix PNG width to 900px, otherwise some flags (e.g. [Norway](https://commons.wikimedia.org/wiki/File:Flag_of_Norway.svg)) are unusable due to tiny dimensions:
```
...
<title>Flag of Norway</title>
	<rect width="22" height="16" fill="#ba0c2f"/>
...
```

PS. 1200px was arbitrary selected, open to suggestions.

### CODE REVIEW

**Comment by dscorbett** [comment]
The new SVG for New Caledonia has two flags in one image. According to https://emojipedia.org/flag-new-caledonia/, all vendors use the flag shown at [File:Flag_of_FLNKS.svg](https://commons.wikimedia.org/wiki/File:Flag_of_FLNKS.svg).

**Comment by SaveTheRbtz** [comment]
Nice catch!  How do you usually handle problems like these?  Do you work with Wikipedia editors or put overrides into the code?

**Comment by dscorbett** [comment]
I would add an override to data/ALIASES-WP.

**Comment by behdad** [comment]
> PS. 1200px was arbitrary selected, open to suggestions.

512?

**Comment by behdad** [comment]
> 512?

900 looks common in the existing files.

**Comment by SaveTheRbtz** [comment]
Ref: 900px size was eventually changed to 1024 in fonttools/region-flags#50

**Pull request merged**
